import { motion } from "framer-motion";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Code2, Zap, Shield, Download, Sparkles, ArrowRight, Check } from "lucide-react";

const features = [
  { icon: Sparkles, title: "AI-Powered Generation", desc: "Generate clean, production-ready code in seconds using advanced AI models." },
  { icon: Code2, title: "Multi-Language Support", desc: "Python, JavaScript, Java, C++ and more — write in any language you need." },
  { icon: Download, title: "Export Anywhere", desc: "Download your code as .py, .txt files or generate beautiful PDFs instantly." },
  { icon: Shield, title: "Secure & Private", desc: "Your prompts and code are encrypted. We never share your data." },
  { icon: Zap, title: "Lightning Fast", desc: "Get results in under 3 seconds with streaming code generation." },
  { icon: ArrowRight, title: "History & Tracking", desc: "All your prompts are saved. Search, revisit, and build on previous work." },
];

const pricingPlans = [
  {
    name: "Free",
    price: "$0",
    period: "forever",
    features: ["5 prompts per day", "All languages", "Code export (.txt, .py)", "Basic history"],
    cta: "Get Started",
    highlight: false,
  },
  {
    name: "Pro",
    price: "$19",
    period: "/month",
    features: ["Unlimited prompts", "All languages", "PDF export", "Priority generation", "Full history", "Priority support"],
    cta: "Upgrade to Pro",
    highlight: true,
  },
];

export default function LandingPage() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background text-foreground">
      {/* Hero */}
      <section className="relative overflow-hidden py-24 md:py-36">
        <div className="absolute inset-0 bg-gradient-hero" />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 h-[600px] w-[600px] rounded-full bg-primary/5 blur-[120px]" />
        <div className="container relative mx-auto px-4 text-center">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7 }}
          >
            <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/5 px-4 py-1.5 text-sm text-primary">
              <Code2 className="h-4 w-4" />
              Code AI
            </div>
            <h1 className="mx-auto max-w-4xl text-4xl font-black leading-tight tracking-tight md:text-7xl">
              Write Code at the
              <br />
              <span className="text-gradient">Speed of Thought</span>
            </h1>
            <p className="mx-auto mt-6 max-w-2xl text-lg text-muted-foreground md:text-xl">
              Describe what you need in plain English. Code AI generates clean,
              production-ready code in Python, JavaScript, Java, C++ and more.
            </p>
            <div className="mt-10 flex flex-col items-center justify-center gap-4 sm:flex-row">
              <Button
                size="lg"
                className="bg-gradient-primary text-primary-foreground px-8 text-base font-semibold hover:opacity-90 glow"
                onClick={() => navigate("/register")}
              >
                Start Generating — Free
                <ArrowRight className="ml-2 h-4 w-4" />
              </Button>
              <Button
                variant="outline"
                size="lg"
                className="text-base border-border hover:bg-secondary"
                onClick={() => navigate("/pricing")}
              >
                View Pricing
              </Button>
            </div>
          </motion.div>

          {/* Code preview mockup */}
          <motion.div
            initial={{ opacity: 0, y: 50 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.3 }}
            className="mx-auto mt-16 max-w-3xl"
          >
            <div className="rounded-xl border border-border/50 bg-card p-1 glow">
              <div className="flex items-center gap-2 border-b border-border/50 px-4 py-3">
                <div className="h-3 w-3 rounded-full bg-destructive/60" />
                <div className="h-3 w-3 rounded-full bg-yellow-500/60" />
                <div className="h-3 w-3 rounded-full bg-green-500/60" />
                <span className="ml-2 text-xs text-muted-foreground font-mono">main.py</span>
              </div>
              <pre className="p-6 text-left text-sm leading-relaxed font-mono text-muted-foreground overflow-x-auto">
                <code>
{`# Generated by Code AI
def fibonacci(n: int) -> list[int]:
  """Generate Fibonacci sequence up to n terms."""
  if n <= 0:
    return []
    
  sequence = [0, 1]
  for i in range(2, n):
    sequence.append(sequence[-1] + sequence[-2])
    
  return sequence[:n]

# Example usage
result = fibonacci(10)
print(f"First 10 Fibonacci numbers: {result}")`}
                </code>
              </pre>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Features */}
      <section className="py-24 border-t border-border/30">
        <div className="container mx-auto px-4">
          <div className="mb-16 text-center">
            <h2 className="text-3xl font-bold md:text-4xl">
              Everything You Need to <span className="text-gradient">Ship Faster</span>
            </h2>
            <p className="mx-auto mt-4 max-w-xl text-muted-foreground">
              From prompt to production code in seconds. No context switching, no boilerplate.
            </p>
          </div>
          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
            {features.map((f, i) => (
              <motion.div
                key={f.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className="group rounded-xl border border-border/50 bg-card p-6 transition-all hover:border-primary/30 hover:glow"
              >
                <div className="mb-4 inline-flex rounded-lg bg-primary/10 p-3">
                  <f.icon className="h-5 w-5 text-primary" />
                </div>
                <h3 className="mb-2 text-lg font-semibold text-foreground">{f.title}</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">{f.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="py-24 border-t border-border/30">
        <div className="container mx-auto px-4">
          <div className="mb-16 text-center">
            <h2 className="text-3xl font-bold md:text-4xl">
              Simple, <span className="text-gradient">Transparent</span> Pricing
            </h2>
            <p className="mx-auto mt-4 max-w-xl text-muted-foreground">
              Start free. Upgrade when you need more.
            </p>
          </div>
          <div className="mx-auto grid max-w-3xl gap-8 md:grid-cols-2">
            {pricingPlans.map((plan) => (
              <div
                key={plan.name}
                className={`rounded-xl border p-8 transition-all ${
                  plan.highlight
                    ? "border-primary/50 bg-card glow relative"
                    : "border-border/50 bg-card"
                }`}
              >
                {plan.highlight && (
                  <div className="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full bg-gradient-primary px-4 py-1 text-xs font-semibold text-primary-foreground">
                    Most Popular
                  </div>
                )}
                <h3 className="text-xl font-bold text-foreground">{plan.name}</h3>
                <div className="mt-4 flex items-baseline gap-1">
                  <span className="text-4xl font-black text-foreground">{plan.price}</span>
                  <span className="text-muted-foreground">{plan.period}</span>
                </div>
                <ul className="mt-6 space-y-3">
                  {plan.features.map((f) => (
                    <li key={f} className="flex items-center gap-2 text-sm text-muted-foreground">
                      <Check className="h-4 w-4 text-primary flex-shrink-0" />
                      {f}
                    </li>
                  ))}
                </ul>
                <Button
                  className={`mt-8 w-full ${
                    plan.highlight
                      ? "bg-gradient-primary text-primary-foreground hover:opacity-90"
                      : "bg-secondary text-secondary-foreground hover:bg-secondary/80"
                  }`}
                  onClick={() => navigate("/register")}
                >
                  {plan.cta}
                </Button>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-border/30 py-12">
        <div className="container mx-auto px-4 text-center">
          <div className="flex items-center justify-center gap-2 text-muted-foreground">
            <Code2 className="h-5 w-5 text-primary" />
            <span className="font-semibold text-foreground">Code AI</span>
          </div>
          <p className="mt-3 text-sm text-muted-foreground">
            © {new Date().getFullYear()} Code AI. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
}
